export const imageMap = {
      mojito: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=720&q=82",
      iceTea: "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=720&q=82",
      milkshake: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=720&q=82",
      icedCoffee: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=720&q=82",
      matcha: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=720&q=82",
      boba: "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=720&q=82",
      frappe: "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=720&q=82",
      frappuccino: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=720&q=82",
      smoothie: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=720&q=82",
      bonbon: "https://images.unsplash.com/photo-1568901839119-631418a3910d?auto=format&fit=crop&w=720&q=82",
      hotDrinks: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=720&q=82",
      espresso: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=720&q=82",
      waffle: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=720&q=82"
    };

export const categories = [
      { id: "all", label: "الكل" },
      { id: "mojito", label: "موهيتو" },
      { id: "mojito-mix", label: "ميكس موهيتو" },
      { id: "ice-tea", label: "آيس تي" },
      { id: "milkshake", label: "ميلك شيك" },
      { id: "iced-coffee", label: "آيسد كوفي" },
      { id: "matcha", label: "ماتشا" },
      { id: "boba", label: "بوبا" },
      { id: "frappe", label: "فرابيه" },
      { id: "frappuccino", label: "فرابتشينو" },
      { id: "smoothie", label: "سموذي" },
      { id: "bonbon", label: "بون بون" },
      { id: "hot-drinks", label: "مشروبات ساخنة" },
      { id: "espresso", label: "إسبريسو" },
      { id: "waffle", label: "وافل" }
    ];

export const menuItems = [
      ["mojito", "mojito", "Mojito Passion Fruit", "موهيتو باشن فروت", imageMap.mojito],
      ["mojito", "mojito", "Mojito Blueberry", "موهيتو بلو بيري", imageMap.mojito],
      ["mojito", "mojito", "Mojito Blue Curacao", "موهيتو بلو كوراساو", imageMap.mojito],
      ["mojito", "mojito", "Mojito Cola", "موهيتو كولا", imageMap.mojito],
      ["mojito", "mojito", "Mojito Red Bull", "موهيتو ريد بول", imageMap.mojito],
      ["mojito", "mojito", "Mojito Red Berry", "موهيتو توت أحمر", imageMap.mojito],
      ["mojito", "mojito", "Mojito Cherry", "موهيتو كرز", imageMap.mojito],
      ["mojito", "mojito", "Mojito Cherry Cola", "موهيتو شيري كولا", imageMap.mojito],
      ["mojito", "mojito", "Mojito Watermelon", "موهيتو بطيخ", imageMap.mojito],
      ["mojito", "mojito", "Mojito Strawberry", "موهيتو فراولة", imageMap.mojito],
      ["mojito", "mojito", "Mojito Pineapple", "موهيتو أناناس", imageMap.mojito],
      ["mojito", "mojito", "Mojito Peach", "موهيتو خوخ", imageMap.mojito],
      ["mojito", "mojito", "Mojito Sunrise", "موهيتو صن رايز", imageMap.mojito],
      ["mojito", "mojito", "Mojito Sunshine", "موهيتو صن شاين", imageMap.mojito],
      ["mojito-mix", "mojito mix", "Mix Peach / Apple", "ميكس خوخ / تفاح", imageMap.mojito],
      ["mojito-mix", "mojito mix", "Mix Peach / Strawberry", "ميكس خوخ / فراولة", imageMap.mojito],
      ["mojito-mix", "mojito mix", "Mix Peach / Pineapple", "ميكس خوخ / أناناس", imageMap.mojito],
      ["mojito-mix", "mojito mix", "Mix Pineapple / Strawberry", "ميكس أناناس / فراولة", imageMap.mojito],
      ["mojito-mix", "mojito mix", "Mix Pineapple / Passion Fruit", "ميكس أناناس / باشن فروت", imageMap.mojito],
      ["mojito-mix", "mojito mix", "Mix Passion Fruit / Strawberry", "ميكس باشن فروت / فراولة", imageMap.mojito],

      ["ice-tea", "ice tea", "Ice Tea Cherry Lemon", "آيس تي كرز ليمون", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Pomegranate", "آيس تي رمان", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Pomegranate Mint", "آيس تي رمان نعناع", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Pineapple", "آيس تي أناناس", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Strawberry", "آيس تي فراولة", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Peach Passion Fruit", "آيس تي خوخ باشن فروت", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Blueberry", "آيس تي بلو بيري", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Cherry", "آيس تي كرز", imageMap.iceTea],
      ["ice-tea", "ice tea", "Blue Ice Tea", "بلو آيس تي", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea", "آيس تي", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Lemon", "آيس تي ليمون", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Passion Fruit", "آيس تي باشن فروت", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Lemon Mint", "آيس تي ليمون نعناع", imageMap.iceTea],
      ["ice-tea", "ice tea", "Ice Tea Peach", "آيس تي خوخ", imageMap.iceTea],

      ["milkshake", "milkshake", "Caramel Milkshake", "ميلك شيك كراميل", imageMap.milkshake],
      ["milkshake", "milkshake", "Chocolate Milkshake", "ميلك شيك شوكولاتة", imageMap.milkshake],
      ["milkshake", "milkshake", "Vanilla Milkshake", "ميلك شيك فانيليا", imageMap.milkshake],
      ["milkshake", "milkshake", "Oreo Milkshake", "ميلك شيك أوريو", imageMap.milkshake],
      ["milkshake", "milkshake", "Banana Milkshake", "ميلك شيك موز", imageMap.milkshake],
      ["milkshake", "milkshake", "Lotus Milkshake", "ميلك شيك لوتس", imageMap.milkshake],
      ["milkshake", "milkshake", "Blueberry Milkshake", "ميلك شيك بلو بيري", imageMap.milkshake],
      ["milkshake", "milkshake", "Kiwi Milkshake", "ميلك شيك كيوي", imageMap.milkshake],
      ["milkshake", "milkshake", "Pineapple Milkshake", "ميلك شيك أناناس", imageMap.milkshake],
      ["milkshake", "milkshake", "Peach Milkshake", "ميلك شيك خوخ", imageMap.milkshake],
      ["milkshake", "milkshake", "Strawberry Milkshake", "ميلك شيك فراولة", imageMap.milkshake],
      ["milkshake", "milkshake", "Cantaloupe Milkshake", "ميلك شيك كنتالوب", imageMap.milkshake],
      ["milkshake", "milkshake", "Passion Fruit Milkshake", "ميلك شيك باشن فروت", imageMap.milkshake],
      ["milkshake", "milkshake", "Watermelon Milkshake", "ميلك شيك بطيخ", imageMap.milkshake],
      ["milkshake", "milkshake", "Guava Milkshake", "ميلك شيك جوافة", imageMap.milkshake],
      ["milkshake", "milkshake", "Mango Milkshake", "ميلك شيك مانجا", imageMap.milkshake],

      ["iced-coffee", "iced coffee", "Ice Latte", "آيس لاتيه", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Mocha", "آيس موكا", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Caramel", "آيس كراميل", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Iced Vanilla", "آيس فانيليا", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Latte Hazelnut", "آيس لاتيه بندق", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Caramel Macchiato", "آيس كراميل ميكاتو", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Matcha", "آيس ماتشا", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Americano", "آيس أمريكانو", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Cappuccino Classic", "آيس كابتشينو كلاسيك", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Cappuccino Caramel", "آيس كابتشينو كراميل", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Cappuccino Hazelnut", "آيس كابتشينو بندق", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Cappuccino Vanilla", "آيس كابتشينو فانيليا", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Spanish Latte Classic", "آيس سبانش لاتيه كلاسيك", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Spanish Latte Vanilla", "آيس سبانش لاتيه فانيليا", imageMap.icedCoffee],
      ["iced-coffee", "iced coffee", "Ice Spanish Latte Hazelnut", "آيس سبانش لاتيه بندق", imageMap.icedCoffee],

      ["matcha", "matcha", "Matcha Blueberry", "ماتشا بلوبيري", imageMap.matcha],
      ["matcha", "matcha", "Matcha Mango", "ماتشا مانجا", imageMap.matcha],
      ["matcha", "matcha", "Matcha Strawberry", "ماتشا فراولة", imageMap.matcha],
      ["matcha", "matcha", "Matcha Raspberry", "ماتشا راس بيري", imageMap.matcha],
      ["matcha", "matcha", "Matcha Coconut", "ماتشا كوكونت", imageMap.matcha],
      ["matcha", "matcha", "Classic Matcha", "ماتشا بس", imageMap.matcha],
      ["boba", "boba", "Boba Coffee", "بوبا كوفي", imageMap.boba],
      ["boba", "boba", "Boba Berry", "بوبا توت", imageMap.boba],
      ["boba", "boba", "Boba Strawberry", "بوبا فراولة", imageMap.boba],
      ["boba", "boba", "Boba Mango", "بوبا مانجا", imageMap.boba],
      ["boba", "boba", "Boba Cherry Cola", "بوبا شيري كولا", imageMap.boba],

      ["frappe", "frappe", "Vanilla Frappe", "فرابيه فانيليا", imageMap.frappe],
      ["frappe", "frappe", "Frappe Chocolate", "فرابيه شوكولاتة", imageMap.frappe],
      ["frappe", "frappe", "Frappe Caramel", "فرابيه كراميل", imageMap.frappe],
      ["frappe", "frappe", "Frappe Lotus", "فرابيه لوتس", imageMap.frappe],
      ["frappe", "frappe", "Frappe Hazelnut", "فرابيه بندق", imageMap.frappe],
      ["frappe", "frappe", "Frappe Matcha", "فرابيه ماتشا", imageMap.frappe],
      ["frappe", "frappe", "Frappe Chocolate Lotus", "فرابيه شوكولاتة لوتس", imageMap.frappe],
      ["frappuccino", "frappuccino", "Caramel Frappuccino", "فرابتشينو كراميل", imageMap.frappuccino],
      ["frappuccino", "frappuccino", "Chocolate Frappuccino", "فرابتشينو شوكولاتة", imageMap.frappuccino],
      ["frappuccino", "frappuccino", "Hazelnut Frappuccino", "فرابتشينو بندق", imageMap.frappuccino],
      ["frappuccino", "frappuccino", "Vanilla Frappuccino", "فرابتشينو فانيليا", imageMap.frappuccino],
      ["frappuccino", "frappuccino", "Matcha Frappuccino", "فرابتشينو ماتشا", imageMap.frappuccino],
      ["frappuccino", "frappuccino", "Lotus Frappuccino", "فرابتشينو لوتس", imageMap.frappuccino],

      ["smoothie", "smoothie", "Watermelon Smoothie", "سموزي بطيخ", imageMap.smoothie],
      ["smoothie", "smoothie", "Watermelon Mint Smoothie", "سموزي بطيخ نعناع", imageMap.smoothie],
      ["smoothie", "smoothie", "Watermelon Lemon Smoothie", "سموزي بطيخ ليمون", imageMap.smoothie],
      ["smoothie", "smoothie", "Watermelon Lemon Mint Smoothie", "سموزي بطيخ ليمون نعناع", imageMap.smoothie],
      ["smoothie", "smoothie", "Watermelon Pineapple Smoothie", "سموزي بطيخ أناناس", imageMap.smoothie],
      ["smoothie", "smoothie", "Watermelon Pineapple Lemon Smoothie", "سموزي بطيخ أناناس ليمون", imageMap.smoothie],
      ["smoothie", "smoothie", "Blueberry Strawberry Smoothie", "سموزي بلو بيري فراولة", imageMap.smoothie],
      ["smoothie", "smoothie", "Pineapple Smoothie", "سموزي أناناس", imageMap.smoothie],
      ["smoothie", "smoothie", "Lemon Smoothie", "سموزي ليمون", imageMap.smoothie],
      ["smoothie", "smoothie", "Lemon Peach Smoothie", "سموزي ليمون خوخ", imageMap.smoothie],
      ["smoothie", "smoothie", "Lemon Strawberry Smoothie", "سموزي ليمون فراولة", imageMap.smoothie],
      ["smoothie", "smoothie", "Lemon Blueberry Smoothie", "سموزي ليمون بلو بيري", imageMap.smoothie],
      ["smoothie", "smoothie", "Lemon Kiwi Smoothie", "سموزي ليمون كيوي", imageMap.smoothie],
      ["smoothie", "smoothie", "Lemon Coconut Smoothie", "سموزي ليمون كوكوت", imageMap.smoothie],
      ["smoothie", "smoothie", "Peach Smoothie", "سموزي خوخ", imageMap.smoothie],
      ["smoothie", "smoothie", "Kiwi Smoothie", "سموزي كيوي", imageMap.smoothie],
      ["smoothie", "smoothie", "Passion Fruit Smoothie", "سموزي باشن فروت", imageMap.smoothie],
      ["smoothie", "smoothie", "Mango Smoothie", "سموزي مانجا", imageMap.smoothie],
      ["smoothie", "smoothie", "Blueberry Smoothie", "سموزي بلو بيري", imageMap.smoothie],
      ["smoothie", "smoothie", "Strawberry Smoothie", "سموزي فراولة", imageMap.smoothie],
      ["smoothie", "smoothie", "Strawberry Mint Smoothie", "سموزي فراولة نعناع", imageMap.smoothie],
      ["smoothie", "smoothie", "Blueberry Lemon Smoothie", "سموزي بلو بيري ليمون", imageMap.smoothie],

      ["bonbon", "bon bon", "Guava / Pineapple", "جوافة / أناناس", imageMap.bonbon],
      ["bonbon", "bon bon", "Guava / Passion Fruit", "جوافة / باشن فروت", imageMap.bonbon],
      ["bonbon", "bon bon", "Guava / Peach", "جوافة / خوخ", imageMap.bonbon],
      ["bonbon", "bon bon", "Guava / Strawberry", "جوافة / فراولة", imageMap.bonbon],
      ["bonbon", "bon bon", "Guava / Blueberry", "جوافة / بلو بيري", imageMap.bonbon],
      ["bonbon", "bon bon", "Guava / Coconut", "جوافة / كوكوت", imageMap.bonbon],
      ["bonbon", "bon bon", "Guava / Mango", "جوافة / مانجا", imageMap.bonbon],

      ["hot-drinks", "hot drink", "Flavored Tea", "شاي نكهات", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Coffee", "قهوة تركي", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Turkish Coffee", "قهوة تركية", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "French Coffee", "قهوة فرنسية", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Cinnamon Milk", "حلبة بالحليب", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Fenugreek Milk", "حلبة بالحليب", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Anise", "ينسون", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Hibiscus", "كركديه", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Ginger", "جنزبيل", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Lotus Coffee Vanilla", "لوتس كوفي فانيليا", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Lotus Coffee Hazelnut", "لوتس كوفي بندق", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Lotus Coffee Marshmallow", "لوتس كوفي مارشميلو", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Hot Chocolate", "هوت شوكولاتة", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Lotus Hot Chocolate", "هوت شوكولاتة لوتس", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Hazelnut Hot Chocolate", "هوت شوكولاتة بندق", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Marshmallow Hot Chocolate", "هوت شوكولاتة مارشميلو", imageMap.hotDrinks],
      ["hot-drinks", "hot drink", "Vanilla Hot Chocolate", "هوت شوكولاتة فانيليا", imageMap.hotDrinks],
      ["espresso", "espresso", "Espresso", "إسبريسو", imageMap.espresso],
      ["espresso", "espresso", "Americano", "أمريكانو", imageMap.espresso],
      ["espresso", "espresso", "Macchiato", "ميكاتو", imageMap.espresso],
      ["espresso", "espresso", "Latte", "لاتيه", imageMap.espresso],
      ["espresso", "espresso", "Mocha Latte", "موكا لاتيه", imageMap.espresso],
      ["espresso", "espresso", "Caramel Latte", "كراميل لاتيه", imageMap.espresso],
      ["espresso", "espresso", "Hazelnut Latte", "بندق لاتيه", imageMap.espresso],
      ["espresso", "espresso", "Caramel Macchiato", "كراميل ميكاتو", imageMap.espresso],
      ["espresso", "espresso", "Marshmallow Latte", "مارشميلو لاتيه", imageMap.espresso],
      ["espresso", "espresso", "Caramel Macchiato Latte", "كراميل ميكاتو لاتيه", imageMap.espresso],
      ["espresso", "espresso", "Spanish Latte", "سبانش لاتيه", imageMap.espresso],
      ["espresso", "espresso", "Spanish Latte Hazelnut", "سبانش لاتيه بندق", imageMap.espresso],
      ["espresso", "espresso", "Spanish Latte Vanilla", "سبانش لاتيه فانيليا", imageMap.espresso],

      ["waffle", "waffle", "Chocolate Waffle", "وافل شوكولاتة", imageMap.waffle],
      ["waffle", "waffle", "Caramel Waffle", "وافل كراميل", imageMap.waffle],
      ["waffle", "waffle", "Lotus Waffle", "وافل لوتس", imageMap.waffle],
      ["waffle", "waffle", "White Chocolate Waffle", "وافل وايت شوكولاتة", imageMap.waffle],
      ["waffle", "waffle", "Mix Chocolate & Caramel Waffle", "وافل ميكس شوكولاتة وكراميل", imageMap.waffle],
      ["waffle", "waffle", "Mix Caramel & White Chocolate Waffle", "وافل ميكس كراميل ووايت شوكولاتة", imageMap.waffle],
      ["waffle", "waffle", "Mix Oreo & Chocolate Waffle", "وافل ميكس أوريو وشوكولاتة", imageMap.waffle],
      ["waffle", "waffle", "Mix Oreo & Caramel Waffle", "وافل ميكس أوريو وكراميل", imageMap.waffle],
      ["waffle", "waffle", "Mix Chocolate & Ice Cream Waffle", "وافل ميكس شوكولاتة وآيس كريم", imageMap.waffle],
      ["waffle", "waffle", "Mix Lotus & Ice Cream Waffle", "وافل ميكس لوتس وآيس كريم", imageMap.waffle]
    ];
